---
title: "表の出力"
author: "Nishida Norimitsu"
date: "2019/12/10"
output: powerpoint_presentation
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(arsenal)

dat <- read_csv("practice_data1.csv")

hyoucontrol <- 
  tableby.control(
    test          = FALSE,          #検定なし
    total         = FALSE,          #全体集計なし
    digits        = 1,　　          #小数点一桁に
    numeric.stats = "meansd",        #平均値(SD)のみでよい。
    stats.labels  = list(meansd = "平均(SD))"), #ラベルを設定
    numeric.simplify = TRUE,  #1行に出力を抑制
    cat.simplify     = TRUE　 #1行に出力を抑制
  )

dat <- dat %>% 
  mutate(
    treatment = factor(treatment, 
                       levels=c("control","treat"),
                       labels=c("コントロール群","処置群")),
    gender    = factor(gender,
                       levels=c("Female","Male"),
                       labels=c("女性","男性")),
    bpcat     = factor(bpcat,
                       levels=c("normal","Elevated","Htn Stage1","Htn Stage2","Htn Stage3"),
                       labels=c("正常","高値","高血圧1度","高血圧2度","高血圧3度"))
  )

hensulabel <- list(gender = "性別:男性",
                   age    = "年齢",
                   bmi    = "BMI",
                   sbp    = "血圧(収縮期)",
                   dbp    = "血圧(拡張期)",
                   bpcat  = "血圧区分")

hyoug <- tableby(treatment~gender+age+bmi+sbp+dbp+bpcat, 
                 data = dat,control = hyoucontrol)
```

```{r results="asis"}
summary(hyoug, text=TRUE, labelTranslations = hensulabel)
```

いかがでしょうか?
このようにすることで、集計結果を簡単に共有することができると思います。

-----
